# Generated by Django 3.2.5 on 2021-07-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_person_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="city",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="cpf",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="family",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.family"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="geolocation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="ocupation",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
